app:
  name: springboot-jwt-starter

server:
  port: 8080

jwt:
  header: Authorization
  expires_in: 600 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: rocksea

spring:
  profiles:
    active: docker
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      # ddl-auto: create
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/jwt?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: rocksea
    password: gogo1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mobile:
    sitepreference:
      enabled: true
    devicedelegatingviewresolver:
      enabled: true
      normal-prefix: normal
      mobile-prefix: mobile
      tablet-prefix: tablet
